# Generated by Django 5.0.3 on 2024-03-21 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_author_name_remove_author_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
